name: 08.1_akspoc-aks-dev-rg-001

on:
  workflow_dispatch:
    inputs:
      envName: 
        default: "dev"
      working_directory:
        default: "./infrastructure/08_akspoc-aks-env-rg-001/"
      project_id: 
        default : "08.1"
      project:
        default: "akspoc-aks"

      
jobs:

  plan:
    uses: huw564/k8s/.github/workflows/aks_terraform_plan.yml@main
    with:
      working_directory: "${{ github.event.inputs.working_directory }}"
      envFilePath: "${{ github.event.inputs.project_id }}_${{ github.event.inputs.project }}-${{ github.event.inputs.envname }}-rg-001_variables.env"
      envName: "${{ github.event.inputs.envName }}"
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AKSPOC1_KEY: ${{ secrets.AKSPOC1_KEY }}
  apply:
    needs:  plan
    uses: huw564/k8s/.github/workflows/terraform_apply.yml@main
    with:
      working_directory: "${{ github.event.inputs.working_directory }}"
      envFilePath: "${{ github.event.inputs.project_id }}_${{ github.event.inputs.project }}-${{ github.event.inputs.envname }}-rg-001_variables.env"
      envName: "${{ github.event.inputs.envName }}"
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
